# SEE https://chromium.woolyss.com/
# DOWNLOAD CHROMIUM VERSION 125: wget 'https://github.com/macchrome/linchrome/releases/download/v125.6422.113-M125.0.6422.113-r1287751-portable-ungoogled-Lin64/ungoogled-chromium_125.0.6422.113_1.vaapi_linux.tar.xz'

# # also need to install pdftotext
# conda create -n amelie2 python=3.11.8
# conda activate amelie2
# conda install -c conda-forge poppler
# # need bcftools too:
# # this is needed for bcftools and won't be installed automatically;
# #   there some version problem if just installing bcftools;
# #   it installs gsl.so.27 but we need gsl.so.25
# conda install -c conda-forge gsl=2.6
# conda create -n bcftools_env bcftools && conda activate bcftools_env && conda install -c bioconda openssl=1.0 && bcftools
# conda install anaconda::graphviz
# Then set up docling:
#   docling-tools models download
#   then in python: import easyocr; reader = easyocr.Reader(['en'])

# then we also need catdoc. This is not in conda and needs to be installed from github
# git clone 'https://github.com/petewarden/catdoc'
# cd catdoc
# ./configure --prefix=~/opt  (or opt_rocky9)
# make
# make install
# Put the catdoc path into the config.json

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sspsygene_processing"
version = "1.0.0"
description = "SSPsyGene Data Processing"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.1",
    "pyarrow==21.0.0",
]

[project.scripts]
sspsygene = "processing.click.main:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
amelie = []
